/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    ListItemsUploadeds: typeof import('./src/components/ListItemsUploadeds.vue')['default']
    ListUploadedItems: typeof import('./src/components/ListUploadedItems.vue')['default']
    MSWordIcon: typeof import('./src/assets/icons/MSWordIcon.vue')['default']
    VueDragAndDropFile: typeof import('./src/components/VueDragAndDropFile.vue')['default']
  }
}
